project_id = "kizogptkryjjxzlixtqp"

[api]
port = 54321

[db]
port = 54322

[studio]
port = 54323

[inbucket]
port = 54324

[storage]
enabled = false

[auth]
enabled = true

[realtime]
enabled = true

[functions.send-push-notifications]
verify_jwt = true

[db.migrations]
schema_paths = [
  "./schemas/_global/*.sql",
  "./schemas/**/tables/*.sql",
  "./schemas/**/functions/*.sql",
  "./schemas/**/policies/*.sql",
  "./schemas/**/triggers/*.sql",
  "./schemas/**/views/*.sql"
]
