grant execute on function public.register_player(text) to authenticated;
grant execute on function public.get_player() to authenticated;
grant execute on function public.set_last_visited_room(uuid) to authenticated;
grant execute on function public.create_room(text) to authenticated;
grant execute on function public.join_room(text) to authenticated;
grant execute on function public.claim_weekly_points(boolean) to authenticated;
grant execute on function public.create_prediction(uuid, text, text[], timestamptz, uuid) to authenticated;
grant execute on function public.create_series(uuid, text, text, integer) to authenticated;
grant execute on function public.update_series(uuid, text, text, integer) to authenticated;
grant execute on function public.activate_series(uuid) to authenticated;
grant execute on function public.complete_series(uuid) to authenticated;
grant execute on function public.archive_series(uuid) to authenticated;
grant execute on function public.get_room_series(uuid) to authenticated;
grant execute on function public.get_room_series_selector(uuid, uuid, text) to authenticated;
grant execute on function public.get_series_active_predictions(uuid, uuid) to authenticated;
grant execute on function public.get_series_completed_predictions(uuid, uuid) to authenticated;
grant execute on function public.lock_prediction(uuid) to authenticated;
grant execute on function public.resolve_prediction_v2(uuid, uuid, text, uuid, varchar) to authenticated;
grant execute on function public.place_bet(uuid, uuid, integer) to authenticated;
grant execute on function public.cancel_bet(uuid) to authenticated;
grant execute on function public.get_preferences(uuid) to authenticated;
grant execute on function public.update_global_preferences(boolean, boolean, boolean, boolean, boolean, boolean, boolean) to authenticated;
grant execute on function public.update_room_preferences(uuid, boolean, boolean, boolean, boolean, boolean, boolean, boolean) to authenticated;
grant execute on function public.reset_room_preferences(uuid) to authenticated;
grant execute on function public.mark_how_to_play_seen() to authenticated;
grant execute on function public.mark_ratings_tip_seen() to authenticated;
grant execute on function public.upsert_user_push_subscription(jsonb) to authenticated;
grant execute on function public.get_room_leaderboard(uuid, text) to authenticated;
grant execute on function public.get_series_leaderboard(uuid, uuid, text) to authenticated;
grant execute on function public.get_room_weekly_leaderboard(uuid, text) to authenticated;
grant execute on function public.get_latest_room_member_snapshot(uuid, uuid) to authenticated;
grant execute on function public.get_room_prediction_history(uuid, int, timestamptz, uuid, text, text, uuid) to authenticated;
grant execute on function public.get_room_activities(uuid, integer, timestamptz, uuid, text, uuid) to authenticated;
grant execute on function public.get_room_stat_cards(uuid, int) to authenticated;
grant execute on function public.get_room_member_stats(uuid, uuid) to authenticated;
grant execute on function public.get_room_member_recent_predictions(uuid, uuid, int, int) to authenticated;

revoke execute on function public.update_streaks_after_resolution(uuid, uuid, uuid, text) from public;
revoke execute on function public.update_player_stats_after_resolution(uuid, uuid, uuid, text) from public;
revoke execute on function public.update_room_stats_after_resolution(uuid, uuid, uuid, text) from public;
revoke execute on function public.update_prediction_ratings(uuid, uuid, uuid) from public;
